name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # fetch all the branches, not only the current one

          persist-credentials: false

      - name: render
        run: make render

      - uses: camunda/action-git-commit@fix/specific-token
        with:
          commit-message: Commit changes
