name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: render
        run: make render

      - uses: camunda/action-git-commit@v1
        with:
          commit-message: Commit changes
